---

- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: upgrade
      package:
        update_cache: yes
        name: "*"
        state: latest

- name: install i3
  hosts: localhost
  tasks:
    - include_vars: 
        file: main.yml

    - package:
        name:
          - i3
          - picom
          - polybar
          - rofi

    - copy:
        src: files/i3config
        dest: /home/{{ user }}/.config/i3/config
        backup: yes
        owner: "{{ user }}"
        group: "{{ user }}"

    - copy:
        src: files/picom.conf
        dest: /home/{{ user }}/.config/picom/
        owner: "{{ user }}"
        group: "{{ user }}"
        backup: yes

    # - copy:
    #     src: files/config-color.ini
    #     dest: /home/{{ user }}/.config/polybar/config.ini
    #     owner: "{{ user }}"
    #     group: "{{ user }}"
    #     backup: yes

    # - copy:
    #     src: files/launch-newpolybar.sh
    #     dest: /home/{{ user }}/.config/polybar/launch.sh
    #     owner: "{{ user }}"
    #     group: "{{ user }}"
    #     backup: yes

    # - file:
    #     path: /home/{{ user }}/.config/polybar/launch.sh
    #     mode: +x

    - copy:
        src: files/config.rasi
        dest: /home/{{ user }}/.config/rofi/
        owner: "{{ user }}"
        group: "{{ user }}"
        backup: yes

    - copy:
        src: files/tilix.dconf
        dest: /home/{{ user }}/
        owner: "{{ user }}"
        group: "{{ user }}"
        backup: yes

    - copy:
        src: files/Xresources
        dest: /home/{{ user }}/.Xresources
        owner: "{{ user }}"
        group: "{{ user }}"
        backup: yes

    - git:
        repo: https://github.com/polybar/polybar-scripts.git
        dest: /home/{{ user }}/git/polybar
        clone: yes
        update: yes
        force: true

    - file:
        path: /home/{{ user }}/git/polybar
        state: directory
        recurse: yes
        owner: "{{ user }}"
        group: "{{ user }}"

    - git:
        repo: https://github.com/adi1090x/polybar-themes.git
        dest: /home/{{ user }}/git/polybar-themes
        clone: yes
        update: yes
        force: true

    -  unarchive:
        src: files/blocks.tar.gz
        dest: /home/{{ user }}/.config/polybar/
        owner: "{{ user }}"
        group: "{{ user }}"


#- name: install themes
#  tags: themes
#  unarchive:
#    src: files/polybar.tar.gz
#    dest: /home/{{ user }}/.config/polybar/
#    owner: "{{ user }}"
#    group: "{{ user }}"




